### ISSUE TITLE
Parsing (ANLY)

### ISSUE THREAD

**Issue by Ptiful** [Mourad-Amj/akk_search_tool#3]
1- Documents Parlementaires - Said & Melike
2- Documents Parlementaires - Said
3- Séances Plénières integral - Maciej
4- Commissions integral - Mourad & Natalia
5- Bulletins des questions et réponses écrites - Ramina
6- Rapports déposés en exécution d'une loi - Sarkis
Agenda - Yuliya

**Comment by melikkekaya** [comment]
Notes for engineers:

**1 & 2 - Documents Parlementaires **(aperçu complet and recent) ****
(at least these info, if available: )
- Document Number --> (3522)
- Page's main url from previous page --> (https://www.lachambre.be/kvvcr/showpage.cfm?section=/flwb&language=fr&cfm=/site/wwwcfm/flwb/flwbn.cfm?lang=F&legislat=55&dossierID=3522)
- First title --> (Document parlementaire 55K3522)
- Main title --> (L'évolution de la dette de l'État fédéral - Audition de M. Jean Deboutte, directeur de l'Agence fédérale de la dette, M. Maric Post, directeur Trésorerie et Marchés des Capitaux de l'Agence fédérale de la dette..)
- URL of pdf --> (Document Chambre: 55K3522001)
- Name of pdf --> (Document Chambre: 55K3522001 )
- Date --> (Date de dépôt: 04/08/2023)
- Type --> (Type de document : 23 RAPPORT)
- Stakeholders --> (Auteur(s): Député actuel Benoît, Piedboeuf MR (AUTEUR))
- Commission --> (COMMISSION CHAMBRE: FINANCES ET BUDGET   (PUBLIC))    *(ps. sometimes more than one, first is enough in that case)*
- Keywords1 --> (Descripteur Eurovoc principal: TRANSPORT FERROVIAIRE)
- Keywords2--> (Descripteurs Eurovoc: REGIONALISATION | TRANSPORT FERROVIAIRE)
- Keywords3 --> (Mots-clés libres: PENSIONS)

3- Séances Plénières integral - 

4- Commissions integral - 

5- Bulletins des questions et réponses écrites - 

6- Rapports déposés en exécution d'une loi - It will be scraped fully.

Agenda -
